import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#c6c6cd",
        "background": "#fcf9f4",
        "on-secondary-fixed": "#111c2d",
        "error-container": "#ffdad6",
        "secondary": "#545f73",
        "surface-variant": "#e5e2dd",
        "tertiary-container": "#251a00",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#ebe8e3",
        "surface-bright": "#fcf9f4",
        "on-secondary-fixed-variant": "#3c475a",
        "surface-container": "#f0ede9",
        "error": "#ba1a1a",
        "secondary-container": "#d5e0f8",
        "on-tertiary-fixed": "#251a00",
        "secondary-fixed": "#d8e3fb",
        "primary": "#000000",
        "on-error": "#ffffff",
        "on-surface-variant": "#45464d",
        "on-tertiary-fixed-variant": "#5b4300",
        "outline": "#76777d",
        "on-primary-fixed": "#131b2e",
        "tertiary-fixed": "#ffdf9d",
        "inverse-on-surface": "#f3f0eb",
        "on-secondary-container": "#586377",
        "on-tertiary-container": "#9e803a",
        "on-surface": "#1c1c19",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "primary-fixed": "#dae2fd",
        "on-tertiary": "#ffffff",
        "surface-dim": "#dcdad5",
        "on-primary-fixed-variant": "#3f465c",
        "surface-tint": "#565e74",
        "on-primary-container": "#7c839b",
        "tertiary": "#000000",
        "tertiary-fixed-dim": "#e6c275",
        "inverse-surface": "#31302d",
        "on-background": "#1c1c19",
        "secondary-fixed-dim": "#bcc7de",
        "surface": "#fcf9f4",
        "primary-fixed-dim": "#bec6e0",
        "inverse-primary": "#bec6e0",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e5e2dd",
        "primary-container": "#131b2e",
        "surface-container-low": "#f6f3ee",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Plus Jakarta Sans", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
